"""Abstraction Emergence — higher-order semantic concepts from anchor clusters.

The system detects when multiple anchors form a coherent category and
generates an AbstractNode that captures the invariant structure.

Example:
  "User likes Python for scripting"
  "User writes Flask APIs"
  "User deploys FastAPI with Docker"
       ↓ sleep + abstraction
  AbstractNode: "User is a backend Python developer"

This is Schema formation made real — not just tag-based grouping, but
embedding-cluster-based category emergence.

v0.4 — emergence, not template matching.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from .anchor import Anchor
from .config import Config


@dataclass
class AbstractNode:
    """A higher-order concept that emerged from multiple anchors.

    Not manually created — generated by the system when it detects
    that several anchors form a coherent semantic category.
    """

    id: str
    label: str                        # human-readable label (e.g., "Backend Developer")
    description: str                  # auto-generated summary
    source_anchor_ids: list[str]      # anchors that generated this abstraction
    centroid_embedding: list[float]   # mean of source embeddings
    confidence: float                 # 0..1, how well-established
    level: int = 1                    # abstraction level (1=direct, 2=meta, 3=meta-meta)
    created_at: float = field(default_factory=time.time)
    tags: list[str] = field(default_factory=list)

    @property
    def is_stable(self) -> bool:
        return self.confidence > Config.get().abstraction.stable_confidence


class AbstractionEngine:
    """Detects emergent categories from anchor clusters.

    Uses embedding-based clustering to find groups of anchors that share
    a common semantic subspace, then generates abstract descriptions.
    """

    def __init__(self, min_cluster_size: int | None = None, similarity_threshold: float | None = None):
        c = Config.get().abstraction
        self.min_cluster_size = min_cluster_size if min_cluster_size is not None else c.min_cluster_size
        self.similarity_threshold = similarity_threshold if similarity_threshold is not None else c.similarity_threshold
        self.abstracts: dict[str, AbstractNode] = {}
        self._counter = 0

    def discover(self, anchors: dict[str, Anchor],
                 embeddings: dict[str, list[float]]) -> list[AbstractNode]:
        """Discover emergent categories from a set of anchors.

        Returns newly discovered abstract nodes (does not include existing ones).
        """
        if len(anchors) < self.min_cluster_size:
            return []

        aid_list = list(anchors.keys())
        emb_matrix = np.array([embeddings.get(aid, [0.0]) for aid in aid_list])

        # Compute pairwise cosine similarity matrix
        norms = np.linalg.norm(emb_matrix, axis=1, keepdims=True)
        norms[norms < 1e-8] = 1e-8
        normalized = emb_matrix / norms
        sim_matrix = np.dot(normalized, normalized.T)

        # Find clusters: connected components above threshold
        clusters = self._find_clusters(aid_list, sim_matrix)

        new_abstracts = []
        for cluster in clusters:
            if len(cluster) < self.min_cluster_size:
                continue

            # Check if this cluster is already covered by an existing abstract
            cluster_set = set(cluster)
            already_covered = any(
                set(a.source_anchor_ids).issuperset(cluster_set)
                for a in self.abstracts.values()
            )
            if already_covered:
                continue

            # Compute centroid embedding
            indices = [aid_list.index(aid) for aid in cluster]
            centroid = np.mean(emb_matrix[indices], axis=0).tolist()

            # Generate label from common tags + key terms
            source_anchors = [anchors[aid] for aid in cluster]
            label = self._generate_label(source_anchors)
            description = self._generate_description(source_anchors, label)

            # Confidence = mean intra-cluster similarity
            intra_sims = []
            for i, aid_i in enumerate(cluster):
                for aid_j in cluster[i + 1:]:
                    ii = aid_list.index(aid_i)
                    jj = aid_list.index(aid_j)
                    intra_sims.append(float(sim_matrix[ii, jj]))
            confidence = sum(intra_sims) / max(1, len(intra_sims))

            if confidence < self.similarity_threshold:
                continue

            self._counter += 1
            abstract = AbstractNode(
                id=f"abstract_{self._counter}",
                label=label,
                description=description,
                source_anchor_ids=cluster,
                centroid_embedding=centroid,
                confidence=confidence,
                tags=self._extract_common_tags(source_anchors),
            )
            self.abstracts[abstract.id] = abstract
            new_abstracts.append(abstract)

        return new_abstracts

    def _find_clusters(self, aid_list: list[str],
                       sim_matrix: np.ndarray) -> list[list[str]]:
        """Find connected components in similarity graph."""
        n = len(aid_list)
        adjacency: dict[int, set[int]] = {i: set() for i in range(n)}

        for i in range(n):
            for j in range(i + 1, n):
                if sim_matrix[i, j] > self.similarity_threshold:
                    adjacency[i].add(j)
                    adjacency[j].add(i)

        visited: set[int] = set()
        clusters = []

        for i in range(n):
            if i in visited:
                continue
            # BFS
            component = []
            queue = [i]
            visited.add(i)
            while queue:
                node = queue.pop(0)
                component.append(aid_list[node])
                for neighbor in adjacency[node]:
                    if neighbor not in visited:
                        visited.add(neighbor)
                        queue.append(neighbor)

            clusters.append(component)

        return clusters

    def _generate_label(self, anchors: list[Anchor]) -> str:
        """Generate a human-readable label from a cluster of anchors.

        Uses common tag analysis + key term extraction.
        """
        common_tags = self._extract_common_tags(anchors)
        if common_tags:
            return " + ".join(common_tags[:3])

        # Fallback: use key terms from the most stable anchor
        best = max(anchors, key=lambda a: a.vector.stability)
        words = best.text.lower().split()
        key_terms = [w for w in words if len(w) > 4][:3]
        if key_terms:
            return " ".join(key_terms).title()
        return f"Concept ({len(anchors)} instances)"

    def _generate_description(self, anchors: list[Anchor], label: str) -> str:
        """Auto-generate a description of the abstract concept."""
        common_tags = self._extract_common_tags(anchors)
        tag_str = ", ".join(common_tags[:5]) if common_tags else "various topics"
        return (
            f"Abstract concept '{label}' emerged from {len(anchors)} related memories "
            f"about {tag_str}."
        )

    @staticmethod
    def _extract_common_tags(anchors: list[Anchor]) -> list[str]:
        """Find tags that appear in at least 2 anchors."""
        from collections import Counter
        tag_counter = Counter()
        for a in anchors:
            for tag in a.tags:
                tag_counter[tag] += 1
        return [tag for tag, count in tag_counter.most_common()
                if count >= 2]

    def match(self, embedding: list[float], top_k: int = 3) -> list[tuple[AbstractNode, float]]:
        """Find abstract nodes that match a query embedding.

        Abstract nodes act as higher-level retrieval targets — when you
        query "backend development", it should match the abstract node
        even if individual anchors don't directly mention it.
        """
        if not self.abstracts:
            return []

        scored = []
        for abstract in self.abstracts.values():
            if not abstract.centroid_embedding:
                continue
            sim = self._cosine_sim(embedding, abstract.centroid_embedding)
            scored.append((abstract, sim * abstract.confidence))

        scored.sort(key=lambda x: -x[1])
        return scored[:top_k]

    @staticmethod
    def _cosine_sim(a: list[float], b: list[float]) -> float:
        min_len = min(len(a), len(b))
        if min_len == 0:
            return 0.0
        dot = sum(a[i] * b[i] for i in range(min_len))
        na = math.sqrt(sum(x * x for x in a))
        nb = math.sqrt(sum(x * x for x in b))
        return dot / (na * nb + 1e-8)

    @property
    def stats(self) -> dict:
        if not self.abstracts:
            return {"total_abstracts": 0, "avg_confidence": 0.0, "max_level": 0}
        return {
            "total_abstracts": len(self.abstracts),
            "avg_confidence": sum(a.confidence for a in self.abstracts.values()) / len(self.abstracts),
            "max_level": max(a.level for a in self.abstracts.values()),
            "total_source_anchors": sum(len(a.source_anchor_ids) for a in self.abstracts.values()),
        }


# ── Cross-Session Abstractive Memory ─────────────────────

@dataclass
class PatternMemory:
    """A recurring pattern detected across multiple sessions.

    Unlike AbstractNode (which captures a static category), PatternMemory
    tracks frequency and recurrence of a pattern over time. When a pattern
    appears frequently enough, it's promoted to a stable abstraction.
    """

    id: str
    pattern_text: str               # template describing the pattern
    centroid_embedding: list[float]  # mean of all matching embeddings
    occurrence_count: int = 1       # how many times this pattern has appeared
    source_session_ids: list[str] = field(default_factory=list)  # unique sessions
    source_anchor_ids: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    first_seen: float = field(default_factory=time.time)
    last_seen: float = field(default_factory=time.time)
    stability: float = 0.3          # 0..1, increases with occurrences
    promoted: bool = False          # has been promoted to stable abstraction
    abstract_id: str = ""           # linked AbstractNode ID after promotion

    @property
    def is_recurring(self) -> bool:
        """Pattern is recurring if seen in 3+ sessions or 5+ times."""
        return len(self.source_session_ids) >= 3 or self.occurrence_count >= 5

    @property
    def is_stable(self) -> bool:
        return self.stability > 0.7


class AbstractiveMemoryEngine:
    """Cross-session abstractive memory — converts recurring concrete events
    into stable pattern memories.

    Runs during sleep rebuild. Detects patterns that recur across sessions,
    tracks their frequency, and promotes frequent patterns to stable abstractions.
    Once promoted, the concrete source events decay faster than the pattern.

    Usage:
        engine = AbstractiveMemoryEngine()
        patterns = engine.extract_patterns(graph)
        promoted = engine.promote_stable_patterns(graph)
    """

    def __init__(self,
                 min_occurrences: int = 3,
                 similarity_threshold: float = 0.75,
                 cross_session_bonus: float = 1.3):
        self.min_occurrences = min_occurrences
        self.similarity_threshold = similarity_threshold
        self.cross_session_bonus = cross_session_bonus
        self.patterns: dict[str, PatternMemory] = {}
        self._abstraction_engine: AbstractionEngine | None = None
        self._counter = 0

    @property
    def abstraction_engine(self) -> AbstractionEngine:
        if self._abstraction_engine is None:
            self._abstraction_engine = AbstractionEngine(
                min_cluster_size=self.min_occurrences,
                similarity_threshold=self.similarity_threshold,
            )
        return self._abstraction_engine

    def extract_patterns(self, graph) -> list[PatternMemory]:
        """Extract recurring patterns from a graph by grouping anchors
        across different sessions by semantic similarity.

        Returns newly discovered patterns.
        """
        from collections import defaultdict

        # Step 1: collect anchors by session
        by_session: dict[str, list[str]] = defaultdict(list)
        for aid, a in graph.anchors.items():
            if a.embedding and a.source_session:
                by_session[a.source_session].append(aid)

        if len(by_session) < 2:
            return []  # need at least 2 sessions for cross-session patterns

        # Step 2: for each session, compute session centroid
        session_centroids: dict[str, list[float]] = {}
        for sid, aids in by_session.items():
            embs = [graph.anchors[aid].embedding for aid in aids
                   if aid in graph.anchors and graph.anchors[aid].embedding]
            if not embs:
                continue
            dim = len(embs[0])
            centroid = [0.0] * dim
            for emb in embs:
                for i in range(dim):
                    centroid[i] += emb[i]
            for i in range(dim):
                centroid[i] /= len(embs)
            session_centroids[sid] = centroid

        # Step 3: find anchors that are similar across different sessions
        new_patterns: list[PatternMemory] = []
        seen_pairs: set[tuple[str, str]] = set()

        sessions = list(by_session.keys())
        for i, sid_a in enumerate(sessions):
            for sid_b in sessions[i + 1:]:
                for aid_a in by_session[sid_a]:
                    if aid_a not in graph.anchors:
                        continue
                    a = graph.anchors[aid_a]
                    if not a.embedding:
                        continue
                    for aid_b in by_session[sid_b]:
                        if aid_b not in graph.anchors:
                            continue
                        b = graph.anchors[aid_b]
                        if not b.embedding:
                            continue

                        pair = (aid_a, aid_b) if aid_a < aid_b else (aid_b, aid_a)
                        if pair in seen_pairs:
                            continue
                        seen_pairs.add(pair)

                        sim = _cosine_sim_abstractive(a.embedding, b.embedding)
                        if sim > self.similarity_threshold:
                            # Found a cross-session match — create or update pattern
                            self._counter += 1
                            centroid = [(a.embedding[j] + b.embedding[j]) / 2
                                       for j in range(len(a.embedding))]

                            # Generate pattern text from the shared topic
                            common_tags = list(set(a.tags) & set(b.tags))
                            tag_str = " + ".join(common_tags[:3]) if common_tags else "general pattern"
                            pattern_text = f"[Cross-Session Pattern] {tag_str}: {a.text[:150]}"

                            pattern = PatternMemory(
                                id=f"pattern_{self._counter}",
                                pattern_text=pattern_text[:500],
                                centroid_embedding=centroid,
                                occurrence_count=2,
                                source_session_ids=list({sid_a, sid_b}),
                                source_anchor_ids=[aid_a, aid_b],
                                tags=common_tags,
                                stability=0.3 + sim * 0.2,
                            )
                            self.patterns[pattern.id] = pattern
                            new_patterns.append(pattern)

        return new_patterns

    def promote_stable_patterns(self, graph) -> list[AbstractNode]:
        """Promote patterns that have reached stability threshold to AbstractNodes.

        Creates AbstractNode anchors in the graph and links the source pattern
        anchors via "instance_of" edges. Returns the list of promoted AbstractNodes.
        """
        promoted: list[AbstractNode] = []

        for pattern in list(self.patterns.values()):
            if pattern.promoted:
                continue
            if not pattern.is_recurring:
                continue

            # Create an AbstractNode from this pattern
            abstract_id = f"abstractive_{pattern.id}"
            abstract = AbstractNode(
                id=abstract_id,
                label=f"Pattern: {pattern.pattern_text[:80]}",
                description=pattern.pattern_text,
                source_anchor_ids=list(pattern.source_anchor_ids),
                centroid_embedding=list(pattern.centroid_embedding),
                confidence=min(0.9, pattern.stability),
                level=2,  # cross-session patterns are level 2
                tags=list(pattern.tags),
            )

            # Store in graph
            graph.abstracts[abstract_id] = abstract

            # Create a summary anchor for this pattern
            pattern_anchor = Anchor.create(
                text=pattern.pattern_text[:800],
                tags=pattern.tags + ["abstractive_memory", "cross_session"],
                importance=0.7,
                emotional_valence=0.3,
            )
            pattern_anchor.id = f"anchor_{abstract_id}"
            pattern_anchor.embedding = pattern.centroid_embedding
            pattern_anchor.vector.stability = pattern.stability
            graph.add_anchor(pattern_anchor)

            # Link source anchors to pattern with "instance_of" edges
            decay_factor = 0.5  # concrete events decay faster after abstraction
            for aid in pattern.source_anchor_ids:
                if aid in graph.anchors:
                    graph.add_edge(aid, pattern_anchor.id,
                                   weight=0.6, edge_type="topical",
                                   relation="instance_of", source_type="explicit",
                                   confidence=pattern.stability)
                    # Accelerate decay on concrete events
                    src = graph.anchors[aid]
                    src.vector.stability *= decay_factor
                    src.vector.importance *= 0.8

            pattern.promoted = True
            pattern.abstract_id = abstract_id
            promoted.append(abstract)

        return promoted

    def consolidate_existing_patterns(self, graph) -> dict:
        """Update existing patterns with new matching anchors.

        Scans all anchors for matches to existing patterns, updates occurrence
        counts, and adds new source anchors when found. Returns update stats.
        """
        new_matches = 0
        merged = 0

        for pattern in self.patterns.values():
            for aid, a in graph.anchors.items():
                if aid in pattern.source_anchor_ids:
                    continue
                if not a.embedding:
                    continue
                sim = _cosine_sim_abstractive(a.embedding, pattern.centroid_embedding)
                if sim > self.similarity_threshold:
                    pattern.source_anchor_ids.append(aid)
                    if a.source_session and a.source_session not in pattern.source_session_ids:
                        pattern.source_session_ids.append(a.source_session)
                    pattern.occurrence_count += 1
                    pattern.last_seen = time.time()
                    pattern.stability = min(1.0, pattern.stability + 0.05)
                    # Update centroid
                    n = pattern.occurrence_count
                    for j in range(len(pattern.centroid_embedding)):
                        pattern.centroid_embedding[j] = (
                            pattern.centroid_embedding[j] * (n - 1) + a.embedding[j]
                        ) / n
                    new_matches += 1

        return {"new_matches": new_matches, "merged": merged,
                "total_patterns": len(self.patterns)}

    @property
    def stats(self) -> dict:
        if not self.patterns:
            return {"total_patterns": 0, "promoted": 0, "avg_occurrences": 0}
        return {
            "total_patterns": len(self.patterns),
            "promoted": sum(1 for p in self.patterns.values() if p.promoted),
            "recurring": sum(1 for p in self.patterns.values() if p.is_recurring),
            "avg_occurrences": sum(p.occurrence_count for p in self.patterns.values()) / len(self.patterns),
            "total_sessions": len(set(s for p in self.patterns.values() for s in p.source_session_ids)),
        }


def _cosine_sim_abstractive(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x**2 for x in a))
    nb = math.sqrt(sum(x**2 for x in b))
    return dot / (na * nb + 1e-8)
