"""Abstraction Emergence — higher-order semantic concepts from anchor clusters.

The system detects when multiple anchors form a coherent category and
generates an AbstractNode that captures the invariant structure.

Example:
  "User likes Python for scripting"
  "User writes Flask APIs"
  "User deploys FastAPI with Docker"
       ↓ sleep + abstraction
  AbstractNode: "User is a backend Python developer"

This is Schema formation made real — not just tag-based grouping, but
embedding-cluster-based category emergence.

v0.4 — emergence, not template matching.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from .anchor import Anchor
from .config import Config


@dataclass
class AbstractNode:
    """A higher-order concept that emerged from multiple anchors.

    Not manually created — generated by the system when it detects
    that several anchors form a coherent semantic category.
    """

    id: str
    label: str                        # human-readable label (e.g., "Backend Developer")
    description: str                  # auto-generated summary
    source_anchor_ids: list[str]      # anchors that generated this abstraction
    centroid_embedding: list[float]   # mean of source embeddings
    confidence: float                 # 0..1, how well-established
    level: int = 1                    # abstraction level (1=direct, 2=meta, 3=meta-meta)
    created_at: float = field(default_factory=time.time)
    tags: list[str] = field(default_factory=list)

    @property
    def is_stable(self) -> bool:
        return self.confidence > Config.get().abstraction.stable_confidence


class AbstractionEngine:
    """Detects emergent categories from anchor clusters.

    Uses embedding-based clustering to find groups of anchors that share
    a common semantic subspace, then generates abstract descriptions.
    """

    def __init__(self, min_cluster_size: int | None = None, similarity_threshold: float | None = None):
        c = Config.get().abstraction
        self.min_cluster_size = min_cluster_size if min_cluster_size is not None else c.min_cluster_size
        self.similarity_threshold = similarity_threshold if similarity_threshold is not None else c.similarity_threshold
        self.abstracts: dict[str, AbstractNode] = {}
        self._counter = 0

    def discover(self, anchors: dict[str, Anchor],
                 embeddings: dict[str, list[float]]) -> list[AbstractNode]:
        """Discover emergent categories from a set of anchors.

        Returns newly discovered abstract nodes (does not include existing ones).
        """
        if len(anchors) < self.min_cluster_size:
            return []

        aid_list = list(anchors.keys())
        emb_matrix = np.array([embeddings.get(aid, [0.0]) for aid in aid_list])

        # Compute pairwise cosine similarity matrix
        norms = np.linalg.norm(emb_matrix, axis=1, keepdims=True)
        norms[norms < 1e-8] = 1e-8
        normalized = emb_matrix / norms
        sim_matrix = np.dot(normalized, normalized.T)

        # Find clusters: connected components above threshold
        clusters = self._find_clusters(aid_list, sim_matrix)

        new_abstracts = []
        for cluster in clusters:
            if len(cluster) < self.min_cluster_size:
                continue

            # Check if this cluster is already covered by an existing abstract
            cluster_set = set(cluster)
            already_covered = any(
                set(a.source_anchor_ids).issuperset(cluster_set)
                for a in self.abstracts.values()
            )
            if already_covered:
                continue

            # Compute centroid embedding
            indices = [aid_list.index(aid) for aid in cluster]
            centroid = np.mean(emb_matrix[indices], axis=0).tolist()

            # Generate label from common tags + key terms
            source_anchors = [anchors[aid] for aid in cluster]
            label = self._generate_label(source_anchors)
            description = self._generate_description(source_anchors, label)

            # Confidence = mean intra-cluster similarity
            intra_sims = []
            for i, aid_i in enumerate(cluster):
                for aid_j in cluster[i + 1:]:
                    ii = aid_list.index(aid_i)
                    jj = aid_list.index(aid_j)
                    intra_sims.append(float(sim_matrix[ii, jj]))
            confidence = sum(intra_sims) / max(1, len(intra_sims))

            if confidence < self.similarity_threshold:
                continue

            self._counter += 1
            abstract = AbstractNode(
                id=f"abstract_{self._counter}",
                label=label,
                description=description,
                source_anchor_ids=cluster,
                centroid_embedding=centroid,
                confidence=confidence,
                tags=self._extract_common_tags(source_anchors),
            )
            self.abstracts[abstract.id] = abstract
            new_abstracts.append(abstract)

        return new_abstracts

    def _find_clusters(self, aid_list: list[str],
                       sim_matrix: np.ndarray) -> list[list[str]]:
        """Find connected components in similarity graph."""
        n = len(aid_list)
        adjacency: dict[int, set[int]] = {i: set() for i in range(n)}

        for i in range(n):
            for j in range(i + 1, n):
                if sim_matrix[i, j] > self.similarity_threshold:
                    adjacency[i].add(j)
                    adjacency[j].add(i)

        visited: set[int] = set()
        clusters = []

        for i in range(n):
            if i in visited:
                continue
            # BFS
            component = []
            queue = [i]
            visited.add(i)
            while queue:
                node = queue.pop(0)
                component.append(aid_list[node])
                for neighbor in adjacency[node]:
                    if neighbor not in visited:
                        visited.add(neighbor)
                        queue.append(neighbor)

            clusters.append(component)

        return clusters

    def _generate_label(self, anchors: list[Anchor]) -> str:
        """Generate a human-readable label from a cluster of anchors.

        Uses common tag analysis + key term extraction.
        """
        common_tags = self._extract_common_tags(anchors)
        if common_tags:
            return " + ".join(common_tags[:3])

        # Fallback: use key terms from the most stable anchor
        best = max(anchors, key=lambda a: a.vector.stability)
        words = best.text.lower().split()
        key_terms = [w for w in words if len(w) > 4][:3]
        if key_terms:
            return " ".join(key_terms).title()
        return f"Concept ({len(anchors)} instances)"

    def _generate_description(self, anchors: list[Anchor], label: str) -> str:
        """Auto-generate a description of the abstract concept."""
        common_tags = self._extract_common_tags(anchors)
        tag_str = ", ".join(common_tags[:5]) if common_tags else "various topics"
        return (
            f"Abstract concept '{label}' emerged from {len(anchors)} related memories "
            f"about {tag_str}."
        )

    @staticmethod
    def _extract_common_tags(anchors: list[Anchor]) -> list[str]:
        """Find tags that appear in at least 2 anchors."""
        from collections import Counter
        tag_counter = Counter()
        for a in anchors:
            for tag in a.tags:
                tag_counter[tag] += 1
        return [tag for tag, count in tag_counter.most_common()
                if count >= 2]

    def match(self, embedding: list[float], top_k: int = 3) -> list[tuple[AbstractNode, float]]:
        """Find abstract nodes that match a query embedding.

        Abstract nodes act as higher-level retrieval targets — when you
        query "backend development", it should match the abstract node
        even if individual anchors don't directly mention it.
        """
        if not self.abstracts:
            return []

        scored = []
        for abstract in self.abstracts.values():
            if not abstract.centroid_embedding:
                continue
            sim = self._cosine_sim(embedding, abstract.centroid_embedding)
            scored.append((abstract, sim * abstract.confidence))

        scored.sort(key=lambda x: -x[1])
        return scored[:top_k]

    @staticmethod
    def _cosine_sim(a: list[float], b: list[float]) -> float:
        min_len = min(len(a), len(b))
        if min_len == 0:
            return 0.0
        dot = sum(a[i] * b[i] for i in range(min_len))
        na = math.sqrt(sum(x * x for x in a))
        nb = math.sqrt(sum(x * x for x in b))
        return dot / (na * nb + 1e-8)

    @property
    def stats(self) -> dict:
        if not self.abstracts:
            return {"total_abstracts": 0, "avg_confidence": 0.0, "max_level": 0}
        return {
            "total_abstracts": len(self.abstracts),
            "avg_confidence": sum(a.confidence for a in self.abstracts.values()) / len(self.abstracts),
            "max_level": max(a.level for a in self.abstracts.values()),
            "total_source_anchors": sum(len(a.source_anchor_ids) for a in self.abstracts.values()),
        }
